### ISSUE TITLE
icon_emoji causes bridge to crash.

### ISSUE THREAD

**Issue by Sandelinos** [turt2live/matrix-appservice-webhooks#88]
I've set up the bridge on Debian 10 and every time I send a post with "icon_emoji" specified the bridge crashes.

Here's the crash log.

```
Tue, 20 Jul 2021 15:01:05 GMT sequelize deprecated Model.findById has been deprecated, please use Model.findByPk instead at node_modules/sequelize/lib/model.js:4208:9
Jul-20-2021 18:01:05.192 +03:00 info [WebService [Hook (redacted for obvious reasons)]] Publishing webhook request for processing
[ERROR] TypeError: cheerio is not a function
    at module.exports (/opt/matrix-webhooks/matrix-appservice-webhooks/src/processing/layers/avatar/slack_icon_emoji.js:13:24)
    at layerChain.then (/opt/matrix-webhooks/matrix-appservice-webhooks/src/processing/WebhookReceiver.js:69:75)
    at tryCatcher (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/matrix-webhooks/matrix-appservice-webhooks/node_modules/bluebird/js/release/async.js:15:14)
```
I've checked that cheerio is installed.
```
$ npm ls | grep cheerio
├─┬ cheerio@1.0.0-rc.9
│ ├─┬ cheerio-select@1.4.0
npm ERR! peer dep missing: winston@^3, required by winston-daily-rotate-file@4.5.5
```
npm version is v10.24.0

I'm not familiar with node so if there's any important information I missed tell me.

**Comment by swarnat** [comment]
We also recognized that some time ago. Today I found the time to search the reason.
When I read the changelog of Cheerio, the RC.9, which was released 3 months ago, and is used in "latest" docker tag, contains a breaking change. 

I prepared PR #91, which should fix this problem. Hope it will getting merged.
