### ISSUE TITLE
Keep getting "SQLITE_ERROR: no such table: webhooks" error. Please help?

### ISSUE THREAD

**Issue by nothing2obvi** [turt2live/matrix-appservice-webhooks#95]
I'm not sure what I'm doing wrong...I'm able to invite @_webhook:[mydomainhere] to a room, and then the bot automatically enters the room, but whenever I type "!webhook" into the room I get the error: "There was an error processing your command." And the resulting logs for the webhook container are as such:

`today at 6:54:16 AM Oct-16-2021 11:54:16.447 +00:00 warn [WebhookStore] Changing database path to be data/production.db to ensure data is persisted
today at 6:54:16 AM Oct-16-2021 11:54:16.484 +00:00 info [index] Preparing bridge...
today at 6:54:16 AM Oct-16-2021 11:54:16.485 +00:00 info [WebhookBridge] Constructing bridge
today at 6:54:16 AM Oct-16-2021 11:54:16.485 +00:00 info [WebhookBridge] Starting bridge
today at 6:54:16 AM Oct-16-2021 11:54:16.525 +00:00 info [WebhookBridge] Request to bridge room !IfXizlWcdzQphTEZSn:[mydomainhere]
today at 6:54:16 AM Oct-16-2021 11:54:16.526 +00:00 info [WebhookBridge] Request to bridge room !lLcPNetGaHkUdSoZxr:[mydomainhere]
today at 6:54:16 AM Oct-16-2021 11:54:16.527 +00:00 info [WebhookBridge] Request to bridge room !KSnBHjQxFHJPkKqeQT:[mydomainhere]
today at 6:54:16 AM Oct-16-2021 11:54:16.528 +00:00 info [WebhookBridge] Request to bridge room !sLfioKneaTQfsdUlxF:[mydomainhere]
today at 6:54:25 AM Oct-16-2021 11:54:25.177 +00:00 info [ProvisioningService] Processing create hook request for !sLfioKneaTQfsdUlxF:[mydomainhere] by @[myusername]:[mydomainhere]
today at 6:54:25 AM Oct-16-2021 11:54:25.225 +00:00 error [InteractiveProvisioner] SQLITE_ERROR: no such table: webhooks
today at 6:54:25 AM SequelizeDatabaseError: SQLITE_ERROR: no such table: webhooks
today at 6:54:25 AM     at Query.formatError (/node_modules/sequelize/lib/dialects/sqlite/query.js:431:16)
today at 6:54:25 AM     at afterExecute (/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
today at 6:54:25 AM     at wrappedAfterExecute (/node_modules/sequelize/lib/dialects/sqlite/query.js:256:39)
today at 6:54:25 AM     at replacement (/node_modules/sqlite3/lib/trace.js:19:31)
today at 6:54:25 AM     at Statement.errBack (/node_modules/sqlite3/lib/sqlite3.js:14:21)`

**Comment by ikuradon** [comment]
Are you runnning with docker?
If runnning environment is docker, edit database.json to:
```
{
  "defaultEnv": {
    "ENV": "NODE_ENV"
  },
  "development": {
    "driver": "sqlite3",
    "filename": "data/development.db"
  },
  "production": {
    "driver": "sqlite3",
    "filename": "data/production.db"
  }
}
```
