### ISSUE TITLE
Fresh installation fails to start - this._orm.import is not a function

### ISSUE THREAD

**Issue by lgwapnitsky** [turt2live/matrix-appservice-webhooks#98]
Receiving the mentioned error when starting a new instance after a fresh installation of the bridge

```
(matrix-appservice-webhooks) root@matrix:/opt/matrix-appservice-webhooks# node index.js -p 9000 -c config/config.yaml -f appservice-registration-webhooks.y
aml                                                                                                                                                        
Dec-16-2021 08:15:34.277 -05:00 info [index] Preparing database...                                                                                         
Dec-16-2021 08:15:34.279 -05:00 info [WebhookStore] Running migrations                                                                                     
[INFO] No migrations to run                                                                                                                                
[INFO] Done                                                                                                                                                
(node:13511) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.    
(Use `node --trace-deprecation ...` to show where the warning was created)                                                                                 
Dec-16-2021 08:15:34.505 -05:00 error [WebhookStore] this._orm.import is not a function                                                                    
TypeError: this._orm.import is not a function                                                                                                              
    at WebhookStore._bindModels (/opt/matrix-appservice-webhooks/src/storage/WebhookStore.js:77:46)                                                        
    at /opt/matrix-appservice-webhooks/src/storage/WebhookStore.js:59:22                                                                                   
    at tryCatcher (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/util.js:16:23)                                                         
    at Promise._settlePromiseFromHandler (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:547:31)                              
    at Promise._settlePromise (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:604:18)                                         
    at Promise._settlePromise0 (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:649:10)                                        
    at Promise._settlePromises (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:729:18)                                        
    at Promise._fulfill (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:673:18)                                               
    at /opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/nodeback.js:42:21                                                                  
    at /opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/commands/on-complete.js:26:7                                                            
    at Object.close (/opt/matrix-appservice-webhooks/node_modules/db-migrate-sqlite3/index.js:154:7)                                                       
    at module.exports (/opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/commands/on-complete.js:10:19)                                          
    at /opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/migrator.js:213:13                                                                      
    at Statement.<anonymous> (/opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/migration.js:368:7)                                                  at Statement.replacement (/opt/matrix-appservice-webhooks/node_modules/sqlite3/lib/trace.js:19:31)                                                         at Statement.replacement (/opt/matrix-appservice-webhooks/node_modules/sqlite3/lib/trace.js:19:31)                                                     
Dec-16-2021 08:15:34.506 -05:00 error [Init] Failed to start bridge                                                                                        [ERROR] TypeError: this._orm.import is not a function                                                                                                      
    at WebhookStore._bindModels (/opt/matrix-appservice-webhooks/src/storage/WebhookStore.js:77:46)                                                       
    at /opt/matrix-appservice-webhooks/src/storage/WebhookStore.js:59:22                                                                                  
    at tryCatcher (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/util.js:16:23)                                                        
    at Promise._settlePromiseFromHandler (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:547:31)                             
    at Promise._settlePromise (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:604:18)                                        
    at Promise._settlePromise0 (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:649:10)                                       
    at Promise._settlePromises (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/promise.js:673:18)
    at /opt/matrix-appservice-webhooks/node_modules/bluebird/js/release/nodeback.js:42:21
    at /opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/commands/on-complete.js:26:7
    at Object.close (/opt/matrix-appservice-webhooks/node_modules/db-migrate-sqlite3/index.js:154:7)
    at module.exports (/opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/commands/on-complete.js:10:19)
    at /opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/migrator.js:213:13
    at Statement.<anonymous> (/opt/matrix-appservice-webhooks/node_modules/db-migrate/lib/migration.js:368:7)
    at Statement.replacement (/opt/matrix-appservice-webhooks/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/opt/matrix-appservice-webhooks/node_modules/sqlite3/lib/trace.js:19:31)

```

Advice is needed.

**Comment by lgwapnitsky** [comment]
redid installation. working now
